allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.13'
  - '@biomejs/cli-darwin-arm64@2.5.13'
  - '@biomejs/cli-darwin-x64@2.5.13'
  - '@biomejs/cli-linux-arm64-musl@2.5.13'
  - '@biomejs/cli-linux-arm64@2.5.13'
  - '@biomejs/cli-linux-x64-musl@2.5.13'
  - '@biomejs/cli-linux-x64@2.5.13'
  - '@biomejs/cli-win32-arm64@2.5.13'
  - '@biomejs/cli-win32-x64@2.5.13'
  - '@payloadcms/db-d1-sqlite@3.89.0'
  - '@payloadcms/drizzle@3.89.0'
  - '@payloadcms/graphql@3.89.0'
  - '@payloadcms/next@3.89.0'
  - '@payloadcms/plugin-cloud-storage@3.89.0'
  - '@payloadcms/richtext-lexical@3.89.0'
  - '@payloadcms/storage-r2@3.89.0'
  - '@payloadcms/translations@3.89.0'
  - '@payloadcms/ui@3.89.0'
  - payload@3.89.0
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  dompurify: 3.4.13
  sharp: ^0.35.4
  undici: 7.29.0
