// Generated by `pnpm pull:staging`. Do not edit by hand.
// Re-run `pnpm pull:staging` or `pnpm pull:prod` to refresh from Cloudflare.

import type { StarterPage } from '@/seed/starterContent'

export const homeStarterPage: StarterPage = {
  key: 'home',
  navigationOrder: 0,
  locales: {
    nl: {
      slug: 'home',
      title: 'Ichtus Leuven',
      seo: {
        title: 'Ichtus Leuven',
        description: 'Een open gemeenschap tot eer van God, relevant voor studenten in Leuven.',
        noIndex: false,
      },
      layout: (media) => [
        {
          heading: 'Door en voor studenten.',
          highlight: 'studenten',
          intro:
            'Ichtus Leuven is een protestants-evangelische vereniging door en voor studenten: een open gemeenschap tot eer van God, relevant voor studenten in Leuven.',
          artStyle: 'image',
          image: media['community-park.webp'],
          imagePosition: 'right',
          accent: 'pink',
          blockType: 'hero',
          primaryLink: {
            label: 'Bekijk de agenda',
            type: 'external',
            url: '#agenda',
            newTab: false,
          },
          secondaryLink: {
            label: 'Wat kun je verwachten?',
            type: 'external',
            url: '#eerste-keer',
            newTab: false,
          },
          appearance: {
            background: 'white',
            spacing: 'spacious',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'Zo ziet een avond eruit.',
          intro:
            'Elke woensdagavond komen we samen. Om de twee weken is er een avond met heel de groep: afwisselend een gezellige, interactieve activiteit (een WILD) of een avond met een spreker of workshop, aanbidding en gebed (een GA). De andere weken komen we in kleine kringen samen om te eten en Bijbelstudie te doen.\n\nWil je eens aansluiten? Check onze agenda of stuur ons een berichtje!',
          items: [
            {
              label: 'Wanneer',
              value: 'Woensdagavond',
              detail: 'Meestal om 19:00 (maar check voor het actuele uur de agenda)',
              link: { type: 'internal', newTab: false },
            },
            {
              label: 'Waar',
              value: 'Leuven',
              detail: 'De actuele locatie staat bij de activiteit',
              link: { type: 'internal', newTab: false },
            },
            {
              label: 'Voor wie',
              value: 'Studenten',
              detail: 'Met (nieuwsgierigheid naar) geloof en een warme gemeenschap',
              link: { type: 'internal', newTab: false },
            },
          ],
          blockType: 'infoCards',
          link: {
            label: 'Bekijk de eerstvolgende avond',
            type: 'external',
            url: '#agenda',
            newTab: false,
          },
          appearance: {
            background: 'yellow',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'eerste-keer',
          },
        },
        {
          layout: 'showroom',
          images: [
            { image: media['Ichtus-91.jpg'], alt: 'Samen eten aan één lange tafel in de tuin.' },
            { image: media['Ichtus-88.jpg'], alt: 'Een moment van gebed samen.' },
            { image: media['Ichtus-78.jpg'], alt: 'Bijpraten in de keuken.' },
            { image: media['Ichtus-57.jpg'], alt: 'Een zonnige namiddag in het park.' },
            { image: media['img_0171.jpeg'], alt: 'Samen zingen tijdens een gezamenlijke avond.' },
            { image: media['Ichtus-79.jpg'], alt: 'Napraten in de tuin.' },
          ],
          blockType: 'photoStory',
          appearance: {
            background: 'white',
            spacing: 'compact',
            width: 'narrow',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'over-ons',
          },
        },
        {
          heading: 'De komende activiteiten.',
          intro:
            "Hier vind je onze geplande avonden, kringen en andere activiteiten. Bij de gezamenlijke avonden en de WILD's staat de locatie vermeld. De locatie van de kringavonden wordt binnen de kringen gecommuniceerd.\n\nNiet helemaal duidelijk? Laat het ons weten!",
          emptyMessage:
            'Er staat nu niets gepland. Stuur ons gerust een bericht om te horen wanneer we weer samenkomen.',
          limit: 5,
          selection: 'upcoming',
          blockType: 'eventsList',
          emptyLink: {
            label: 'Stuur een e-mail',
            type: 'external',
            url: 'mailto:leuven@ichtus.be',
            newTab: false,
          },
          events: [],
          calendarLink: { type: 'internal', newTab: false },
          appearance: {
            background: 'white',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'agenda',
          },
        },
        {
          heading: 'Samen groeien in geloof.',
          highlight: 'groeien',
          body: 'Het geloof in Jezus staat centraal. We willen van God en elkaar leren en als kritische jongvolwassenen midden in de samenleving staan.',
          accent: 'pink',
          blockType: 'statement',
          link: {
            label: 'Lees meer over ons',
            type: 'external',
            url: '/nl/over-ons',
            newTab: false,
          },
          appearance: {
            background: 'pink',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'Je eerste keer bij Ichtus.',
          intro:
            'Hier vind je de praktische antwoorden. Staat je vraag er niet bij, stuur ons dan gerust een bericht.',
          items: [
            {
              question: 'Kan ik alleen komen?',
              answer:
                'Zeker, je bent altijd welkom. Stuur ons een mailtje of een berichtje via Instagram als je het fijn vindt dat iemand je bij aankomst opvangt. ',
            },
            {
              question: 'Moet ik christen zijn om te komen?',
              answer:
                'Nee, dat hoeft niet. Het geloof staat centraal, maar iedereen is welkom om aan te sluiten.',
            },
            {
              question: 'Wat doen we tijdens een kringavond?',
              answer:
                'Tweewekelijks komen we op woensdagaovnd samen om in kleinere groepen na te denken over de Bijbel. Deze groepen blijven een heel jaar hetzelfde, waarmee je deze mensen dus het beste leert kennen! De meeste kringen komen samen op iemands kot. Rond 18:30 begint je kring door samen te eten, en daarna ga je in gesprek over de Bijbel en wat die ons te vertellen heeft. De bijbelstudies worden gehouden aan de hand van een kringbundel die voorzien is door Ichtus Vlaanderen. ',
            },
            {
              question: 'Wat doen we tijdens een GA (gemeenschappelijke avond)?',
              answer:
                'Voor een GA komen we rond 18:30 samen om te eten. Daarna beginnen we de avond met samen zingen en gebed. Meestal nodigen we een spreker uit, die hierna met de groep een aspect van het jaarthema verder uitdiept. We proberen rond 22:00 af te sluiten. Voor goede gesprekken kan ja nadien nog mee op café!',
            },
            {
              question: 'Wat doen we tijdens een WILD?',
              answer:
                'Op een WILD-avond doen we iets gezelligs met heel de groep, denk aan bowlen, schaatsen, een quiz, etc. Voor een WILD komen we rond 18:30 samen om te eten, daarna gaan we samen naar de plek waar de WILD doorgaat. Dit zijn de perfecte avonden om elkaar te leren kennen of een vriend(in) mee te nemen!',
            },
            {
              question:
                'Naar welke activiteit kan ik het beste komen als ik nog nooit bij Ichtus ben geweest?',
              answer:
                'Je mag altijd aansluiten, maar het is het leukst als je gelijk de hele groep leert kennen. Daarvoor haak je het beste aan bij een WILD of een GA. Haak je het liefst direct aan bij een kring? Stuur ons dan even een berichtje, dan kijken we samen bij welke kring je het beste kan aansluiten.',
            },
            {
              question: 'Waar vind ik de locatie?',
              answer:
                'De actuele locatie en het tijdstip van de gezamelijke activiteiten staan in de agenda of op onze socials. De locaties van kringavonden worden binnen de kringen afgesproken. Kan je het niet vinden? Voel je vrij om een berichtje te sturen!',
            },
          ],
          blockType: 'faq',
          appearance: {
            background: 'white',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'Zin om kennis te maken?',
          body: 'Bekijk wanneer we samenkomen of stuur ons een bericht. Je hoeft niemand te kennen en je mag gewoon eens komen kijken.',
          accent: 'blue',
          blockType: 'callToAction',
          primaryLink: {
            label: 'Stuur een e-mail',
            type: 'external',
            url: 'mailto:leuven@ichtus.be',
            newTab: false,
          },
          secondaryLink: {
            label: 'Bekijk Instagram',
            type: 'external',
            url: 'https://www.instagram.com/ichtusleuven/',
            newTab: true,
          },
          appearance: {
            background: 'blue',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'kom-mee',
          },
        },
      ],
    },
    en: {
      slug: 'home',
      title: 'Ichtus Leuven',
      seo: {
        title: 'Ichtus Leuven',
        description: 'An open community honouring God, relevant to students in Leuven.',
        noIndex: false,
      },
      layout: (media) => [
        {
          heading: 'By students, for students.',
          highlight: 'students',
          intro:
            'Ichtus Leuven is a Protestant Evangelical association by and for students: an open community honouring God, relevant to students in Leuven.',
          artStyle: 'image',
          image: media['community-park.webp'],
          imagePosition: 'right',
          accent: 'pink',
          blockType: 'hero',
          primaryLink: {
            label: 'View the calendar',
            type: 'external',
            url: '#calendar',
            newTab: false,
          },
          secondaryLink: {
            label: 'What can you expect?',
            type: 'external',
            url: '#first-time',
            newTab: false,
          },
          appearance: {
            background: 'white',
            spacing: 'spacious',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'What an evening looks like.',
          intro:
            'We meet every Wednesday evening. Every other week there is an evening with the whole group: either a relaxed, interactive activity (a WILD) or an evening with a speaker or workshop, worship and prayer (a GA). In the weeks in between we meet in small groups to share a meal and study the Bible.\n\nWould you like to join us? Check our calendar or send us a message!',
          items: [
            {
              label: 'When',
              value: 'Wednesday evening',
              detail: 'Usually at 19:00 (but check the calendar for the current time)',
              link: { type: 'internal', newTab: false },
            },
            {
              label: 'Where',
              value: 'Leuven',
              detail: 'The current location is listed with the activity',
              link: { type: 'internal', newTab: false },
            },
            {
              label: 'Who for',
              value: 'Students',
              detail: 'With faith (or curiosity about it) and a warm community',
              link: { type: 'internal', newTab: false },
            },
          ],
          blockType: 'infoCards',
          link: {
            label: 'View the next evening',
            type: 'external',
            url: '#calendar',
            newTab: false,
          },
          appearance: {
            background: 'yellow',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'first-time',
          },
        },
        {
          layout: 'showroom',
          images: [
            {
              image: media['Ichtus-91.jpg'],
              alt: 'Eating together at one long table in the garden.',
            },
            { image: media['Ichtus-88.jpg'], alt: 'A moment of prayer together.' },
            { image: media['Ichtus-78.jpg'], alt: 'Catching up in the kitchen.' },
            { image: media['Ichtus-57.jpg'], alt: 'A sunny afternoon in the park.' },
            { image: media['img_0171.jpeg'], alt: 'Singing together during a shared evening.' },
            { image: media['Ichtus-79.jpg'], alt: 'Talking on in the garden.' },
          ],
          blockType: 'photoStory',
          appearance: {
            background: 'white',
            spacing: 'compact',
            width: 'narrow',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'about-us',
          },
        },
        {
          heading: 'Upcoming activities.',
          intro:
            'Here you will find our planned evenings, small groups and other activities. The location is listed for the shared evenings and the WILDs. The location of the small group evenings is shared within each group.\n\nNot entirely clear? Let us know!',
          emptyMessage:
            'Nothing is scheduled right now. Send us a message to hear when we will meet again.',
          limit: 5,
          selection: 'upcoming',
          blockType: 'eventsList',
          emptyLink: {
            label: 'Send an email',
            type: 'external',
            url: 'mailto:leuven@ichtus.be',
            newTab: false,
          },
          events: [],
          calendarLink: { type: 'internal', newTab: false },
          appearance: {
            background: 'white',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'calendar',
          },
        },
        {
          heading: 'Growing together in faith.',
          highlight: 'Growing',
          body: 'Faith in Jesus is at the centre. We want to learn from God and from one another and to stand as thoughtful young adults in the middle of society.',
          accent: 'pink',
          blockType: 'statement',
          link: {
            label: 'Read more about us',
            type: 'external',
            url: '/en/about-us',
            newTab: false,
          },
          appearance: {
            background: 'pink',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'Your first time at Ichtus.',
          intro:
            'Here you will find the practical answers. If your question is not listed, feel free to send us a message.',
          items: [
            {
              question: 'Can I come on my own?',
              answer:
                'Absolutely, you are always welcome. Send us an email or a message on Instagram if you would like someone to meet you when you arrive.',
            },
            {
              question: 'Do I need to be a Christian to come?',
              answer: 'No, you do not. Faith is at the centre, but everyone is welcome to join in.',
            },
            {
              question: 'What do we do during a small group evening?',
              answer:
                'Every other Wednesday evening we meet in smaller groups to reflect on the Bible. These groups stay the same all year, so these are the people you get to know best! Most groups meet at someone’s student room. Around 18:30 your group starts by sharing a meal, and afterwards you talk about the Bible and what it has to say to us. The Bible studies follow a study booklet provided by Ichtus Vlaanderen.',
            },
            {
              question: 'What do we do during a GA (shared evening)?',
              answer:
                'For a GA we gather around 18:30 to eat together. We then open the evening by singing and praying together. We usually invite a speaker, who afterwards explores an aspect of the annual theme with the group. We aim to finish around 22:00. If you are up for good conversations, you can join us at a pub afterwards!',
            },
            {
              question: 'What do we do during a WILD?',
              answer:
                'On a WILD evening we do something relaxed with the whole group, such as bowling, ice skating, a quiz, and so on. For a WILD we gather around 18:30 to eat together, and then we head to the place where the WILD takes place. These are the perfect evenings to get to know one another or to bring a friend along!',
            },
            {
              question: 'Which activity is best to come to if I have never been to Ichtus before?',
              answer:
                'You are welcome to join at any time, but it is most fun if you get to know the whole group straight away. A WILD or a GA is the best place to start. Would you rather join a small group right away? Send us a message and we will look together at which group suits you best.',
            },
            {
              question: 'Where can I find the location?',
              answer:
                'The current location and time of the shared activities are listed in the calendar or on our socials. The locations of small group evenings are arranged within each group. Cannot find it? Feel free to send us a message!',
            },
          ],
          blockType: 'faq',
          appearance: {
            background: 'white',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
          },
        },
        {
          heading: 'Want to meet us?',
          body: 'See when we are meeting or send us a message. You do not need to know anyone, and you are welcome to simply come and see.',
          accent: 'blue',
          blockType: 'callToAction',
          primaryLink: {
            label: 'Send an email',
            type: 'external',
            url: 'mailto:leuven@ichtus.be',
            newTab: false,
          },
          secondaryLink: {
            label: 'View Instagram',
            type: 'external',
            url: 'https://www.instagram.com/ichtusleuven/',
            newTab: true,
          },
          appearance: {
            background: 'blue',
            spacing: 'normal',
            width: 'standard',
            alignment: 'left',
            headingSize: 'large',
            anchor: 'join-us',
          },
        },
      ],
    },
  },
}
