/**
 * Turns content that was pulled out of a Cloudflare D1 database into the
 * generated starter-content modules under `src/seed/starter`.
 *
 * The serializer never writes database identifiers into the generated source.
 * Uploads and internal page links are populated by Payload (depth >= 1) and are
 * recognised by their shape, then emitted as `media['file.jpg']` and
 * `pages['over-ons']` lookups that `applyStarterContent` resolves against the
 * database it is seeding.
 */

import type { SeedMediaEntry } from '@/seed/mediaFiles'

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

/**
 * Identifiers and the global discriminator are managed by Payload itself, so
 * they are never written into the generated modules.
 */
const DROPPED_KEYS = new Set(['id', 'createdAt', 'updatedAt', 'globalType'])

export type SerializeResult = {
  /** Media filenames the expression looks up, in first-seen order. */
  media: string[]
  /** Page slugs the expression looks up, in first-seen order. */
  pages: string[]
  source: string
  warnings: string[]
}

type Collector = {
  media: Set<string>
  pages: Set<string>
  warnings: string[]
}

function isMediaDocument(value: object): value is { filename: string } {
  const candidate = value as { filename?: unknown; mimeType?: unknown }
  return typeof candidate.filename === 'string' && typeof candidate.mimeType === 'string'
}

function isPageDocument(value: object): value is { slug: string } {
  const candidate = value as { layout?: unknown; slug?: unknown }
  return typeof candidate.slug === 'string' && Array.isArray(candidate.layout)
}

/** Biome rewrites the quoting, so JSON escaping is enough here. */
export function quote(value: string): string {
  return JSON.stringify(value)
}

function objectKey(key: string): string {
  return IDENTIFIER.test(key) ? key : quote(key)
}

/** `pages.home` reads better than `pages['home']`, where the key allows it. */
function lookup(map: string, key: string): string {
  return IDENTIFIER.test(key) ? `${map}.${key}` : `${map}[${quote(key)}]`
}

function expression(value: unknown, path: string, collector: Collector): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'string') return quote(value)
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null'
  if (typeof value === 'boolean') return String(value)

  if (Array.isArray(value)) {
    const items = value.map((item, index) => expression(item, `${path}[${index}]`, collector))
    return `[${items.join(', ')}]`
  }

  if (typeof value !== 'object') {
    collector.warnings.push(`Dropped unsupported ${typeof value} at ${path}`)
    return 'null'
  }

  if (isMediaDocument(value)) {
    collector.media.add(value.filename)
    return lookup('media', value.filename)
  }

  if (isPageDocument(value)) {
    collector.pages.add(value.slug)
    return lookup('pages', value.slug)
  }

  const entries = Object.entries(value).flatMap(([key, item]) => {
    if (DROPPED_KEYS.has(key)) return []
    if (item === null || item === undefined) return []
    return [`${objectKey(key)}: ${expression(item, `${path}.${key}`, collector)}`]
  })
  return `{ ${entries.join(', ')} }`
}

/**
 * Serializes a value that was read back from the database into TypeScript
 * source, reporting which media files and pages it depends on.
 */
export function serialize(value: unknown, path = 'value'): SerializeResult {
  const collector: Collector = { media: new Set(), pages: new Set(), warnings: [] }
  const source = expression(value, path, collector)
  return {
    media: [...collector.media],
    pages: [...collector.pages],
    source,
    warnings: collector.warnings,
  }
}

/** `(media, pages) => …` with the arguments the body actually reads. */
export function factory(result: SerializeResult): string {
  const media = result.media.length ? 'media' : '_media'
  const parameters = result.pages.length
    ? `(${media}, pages)`
    : result.media.length
      ? '(media)'
      : '()'
  return `${parameters} => (${result.source})`
}

export function camelCase(value: string): string {
  const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean)
  const [first = 'page', ...rest] = parts
  const head = /^[0-9]/.test(first) ? `page${first}` : first
  return (
    head.charAt(0).toLowerCase() +
    head.slice(1) +
    rest.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('')
  )
}

export function moduleFilename(slug: string): string {
  return slug.replace(/[^A-Za-z0-9-_]+/g, '-')
}

const HEADER = [
  '// Generated by `pnpm pull:staging`. Do not edit by hand.',
  '// Re-run `pnpm pull:staging` or `pnpm pull:prod` to refresh from Cloudflare.',
].join('\n')

export function mediaModule(library: Map<string, SeedMediaEntry>): string {
  const entries = [...library.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([filename, entry]) => `  ${quote(filename)}: ${serialize(entry, filename).source},`)
    .join('\n')

  return `${HEADER}

import type { SeedMediaEntry } from '@/seed/mediaFiles'

/**
 * Every media file the starter content refers to. The binaries live in
 * \`public/photos\` so \`pnpm seed\` can upload them into a fresh database.
 */
export const seedMediaLibrary = {
${entries}
} satisfies Record<string, SeedMediaEntry>

export type SeedMediaFilename = keyof typeof seedMediaLibrary

/** Media filenames mapped onto the identifiers of a seeded database. */
export type SeedMediaIDs = Record<SeedMediaFilename, number>
`
}

export type PageLocaleInput = {
  layout: SerializeResult
  navigationLabel?: string | null
  sectionTitle?: string | null
  seo?: unknown
  slug: string
  title: string
}

export type PageModuleInput = {
  key: string
  locales: Record<string, PageLocaleInput>
  navigationOrder?: number | null
  parentSlug?: string | null
}

export function pageModule(page: PageModuleInput): { exportName: string; source: string } {
  const exportName = `${camelCase(page.key)}StarterPage`
  const locales = Object.entries(page.locales)
    .map(([locale, content]) => {
      const fields = [
        `slug: ${quote(content.slug)}`,
        `title: ${quote(content.title)}`,
        content.navigationLabel ? `navigationLabel: ${quote(content.navigationLabel)}` : '',
        content.sectionTitle ? `sectionTitle: ${quote(content.sectionTitle)}` : '',
        content.seo ? `seo: ${serialize(content.seo, `${locale}.seo`).source}` : '',
        `layout: ${factory(content.layout)}`,
      ].filter(Boolean)
      return `    ${locale}: {\n      ${fields.join(',\n      ')},\n    },`
    })
    .join('\n')

  const attributes = [
    `  key: ${quote(page.key)}`,
    page.parentSlug ? `  parentSlug: ${quote(page.parentSlug)}` : '',
    typeof page.navigationOrder === 'number' ? `  navigationOrder: ${page.navigationOrder}` : '',
  ].filter(Boolean)

  const source = `${HEADER}

import type { StarterPage } from '@/seed/starterContent'

export const ${exportName}: StarterPage = {
${attributes.join(',\n')},
  locales: {
${locales}
  },
}
`
  return { exportName, source }
}

export function siteSettingsModule(locales: Record<string, SerializeResult>): string {
  const entries = Object.entries(locales)
    .map(([locale, result]) => `  ${locale}: ${factory(result)},`)
    .join('\n')

  return `${HEADER}

import type { StarterSiteSettings } from '@/seed/starterContent'

export const starterSiteSettings: StarterSiteSettings = {
${entries}
}
`
}

export function indexModule(pages: { exportName: string; filename: string }[]): string {
  const imports = pages
    .map(({ exportName, filename }) => `import { ${exportName} } from './pages/${filename}'`)
    .join('\n')

  return `${HEADER}

import type { StarterPage } from '@/seed/starterContent'

${imports}

export { seedMediaLibrary } from './media'
export type { SeedMediaFilename, SeedMediaIDs } from './media'
export { starterSiteSettings } from './siteSettings'

/** Starter pages in the order they were published on Cloudflare. */
export const starterPages: StarterPage[] = [${pages.map(({ exportName }) => exportName).join(', ')}]
`
}
