// Generated by `pnpm pull:staging`. Do not edit by hand.
// Re-run `pnpm pull:staging` or `pnpm pull:prod` to refresh from Cloudflare.

import type { StarterPage } from '@/seed/starterContent'
import { homeStarterPage } from './pages/home'
import { overOnsStarterPage } from './pages/over-ons'
import { privacyStarterPage } from './pages/privacy'

export type { SeedMediaFilename, SeedMediaIDs } from './media'
export { seedMediaLibrary } from './media'
export { starterSiteSettings } from './siteSettings'

/** Starter pages in the order they were published on Cloudflare. */
export const starterPages: StarterPage[] = [overOnsStarterPage, privacyStarterPage, homeStarterPage]
