// Generated by `pnpm pull:staging`. Do not edit by hand.
// Re-run `pnpm pull:staging` or `pnpm pull:prod` to refresh from Cloudflare.

import type { StarterSiteSettings } from '@/seed/starterContent'

export const starterSiteSettings: StarterSiteSettings = {
  nl: (_media, pages) => ({
    siteName: 'Ichtus Leuven',
    logoAlt: 'Ichtus Leuven',
    navigation: [
      { link: { label: 'over ons', type: 'internal', page: pages['over-ons'], newTab: false } },
      { link: { label: 'kalender', type: 'internal', page: pages.kalender, newTab: false } },
      { link: { label: 'eerste keer?', type: 'external', url: '#eerste-keer', newTab: false } },
    ],
    dutchLabel: 'nl',
    englishLabel: 'en',
    footerLinks: [
      {
        link: { label: 'Privacy & cookies', type: 'internal', page: pages.privacy, newTab: false },
      },
      {
        link: {
          label: 'Instagram',
          type: 'external',
          url: 'https://www.instagram.com/ichtusleuven/',
          newTab: true,
        },
      },
      {
        link: { label: 'E-mail', type: 'external', url: 'mailto:leuven@ichtus.be', newTab: false },
      },
    ],
    email: 'leuven@ichtus.be',
    instagramUrl: 'https://www.instagram.com/ichtusleuven/',
    calendarUrl:
      'https://calendar.google.com/calendar/u/0?cid=NnFtdmQ1ZnBuOHRmb2xjMmZrZ3VlOHNvNjRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ',
    defaultDescription:
      'Ichtus Leuven is een studentenvereninging door en voor studenten met een protestants-evangelisch karakter. We zijn een open gemeenschap tot eer van God, relevant voor studenten in Leuven.',
  }),
  en: (_media, pages) => ({
    siteName: 'Ichtus Leuven',
    logoAlt: 'Ichtus Leuven',
    navigation: [
      { link: { label: 'about us', type: 'internal', page: pages['about-us'], newTab: false } },
      { link: { label: 'calendar', type: 'internal', page: pages.calendar, newTab: false } },
      { link: { label: 'first time?', type: 'external', url: '#first-time', newTab: false } },
    ],
    dutchLabel: 'nl',
    englishLabel: 'en',
    footerLinks: [
      {
        link: { label: 'Privacy & cookies', type: 'internal', page: pages.privacy, newTab: false },
      },
      {
        link: {
          label: 'Instagram',
          type: 'external',
          url: 'https://www.instagram.com/ichtusleuven/',
          newTab: true,
        },
      },
      { link: { label: 'Email', type: 'external', url: 'mailto:leuven@ichtus.be', newTab: false } },
    ],
    email: 'leuven@ichtus.be',
    instagramUrl: 'https://www.instagram.com/ichtusleuven/',
    calendarUrl:
      'https://calendar.google.com/calendar/u/0?cid=NnFtdmQ1ZnBuOHRmb2xjMmZrZ3VlOHNvNjRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ',
    defaultDescription:
      'Ichtus Leuven is a student association by and for students with a Protestant Evangelical character. We are an open community honouring God, relevant to students in Leuven.',
  }),
}
