/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    registrations: Registration;
    'registration-deliveries': RegistrationDelivery;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'registration-deliveries': RegistrationDeliveriesSelect<false> | RegistrationDeliveriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Gebruik “home” voor de startpagina.
   */
  slug: string;
  /**
   * Optioneel: toon deze pagina in de sectienavigatie van een hoofdpagina.
   */
  parent?: (number | null) | Page;
  /**
   * Korte titel voor sectienavigatie.
   */
  navigationLabel?: string | null;
  navigationOrder?: number | null;
  /**
   * Titel boven de sectienavigatie van deze hoofdpagina.
   */
  sectionTitle?: string | null;
  layout: (
    | {
        heading: string;
        highlight?: string | null;
        intro: string;
        primaryLink?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        secondaryLink?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        artStyle?: ('image' | 'none') | null;
        image?: (number | null) | Media;
        /**
         * Wordt gebruikt wanneer geen geüploade afbeelding is gekozen.
         */
        curatedPhoto?:
          | (
              | 'community-garden-game'
              | 'community-park'
              | 'community-park-game'
              | 'community-prayer'
              | 'community-steps'
              | 'community-table'
            )
          | null;
        curatedPhotoAlt?: string | null;
        imagePosition?: ('right' | 'left' | 'background') | null;
        accent?: ('yellow' | 'pink' | 'green' | 'blue') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        items: {
          label: string;
          id?: string | null;
        }[];
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'values';
      }
    | {
        heading: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        items?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        layout?: ('split' | 'centered' | 'imageLeft' | 'imageRight') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        heading: string;
        highlight?: string | null;
        title?: string | null;
        accent?: ('yellow' | 'pink' | 'green' | 'blue') | null;
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'poster';
      }
    | {
        heading: string;
        intro?: string | null;
        emptyMessage?: string | null;
        emptyLink?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        limit?: number | null;
        selection?: ('upcoming' | 'manual') | null;
        events?: (number | Event)[] | null;
        calendarLink?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'eventsList';
      }
    | {
        heading: string;
        intro?: string | null;
        emptyMessage?: string | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'calendar';
      }
    | {
        heading: string;
        highlight?: string | null;
        body: string;
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        accent?: ('yellow' | 'pink' | 'green' | 'blue') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'statement';
      }
    | {
        quote: string;
        body?: string | null;
        attribution?: string | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        heading: string;
        body?: string | null;
        primaryLink: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        secondaryLink?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        accent?: ('yellow' | 'pink' | 'green' | 'blue') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        heading?: string | null;
        images: {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[];
        columns?: ('two' | 'three' | 'mixed') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaGrid';
      }
    | {
        heading: string;
        intro?: string | null;
        items: {
          name: string;
          url: string;
          logo:
            'ichtus-vlaanderen' | 'ichtus-brussels' | 'ichtus-antwerpen' | 'ichtus-gent' | 'ichtus-hasselt' | 'ifes';
          id?: string | null;
        }[];
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'networkLinks';
      }
    | {
        images: {
          /**
           * Upload een nieuwe foto of kies een bestaande foto uit de mediabibliotheek.
           */
          image?: (number | null) | Media;
          /**
           * Optioneel alternatief wanneer geen foto uit de mediabibliotheek is gekozen.
           */
          photo?:
            | (
                | 'community-garden-game'
                | 'community-park'
                | 'community-park-game'
                | 'community-prayer'
                | 'community-steps'
                | 'community-table'
              )
            | null;
          /**
           * Beschrijf wat er op de foto gebeurt. Deze tekst staat altijd onder de foto.
           */
          alt: string;
          id?: string | null;
        }[];
        layout?: ('editorial' | 'wide' | 'showroom') | null;
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'photoStory';
      }
    | {
        heading: string;
        intro?: string | null;
        items: {
          label: string;
          value: string;
          detail?: string | null;
          link?: {
            label?: string | null;
            type?: ('internal' | 'external') | null;
            page?: (number | null) | Page;
            url?: string | null;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[];
        link?: {
          label?: string | null;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'infoCards';
      }
    | {
        heading: string;
        intro?: string | null;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        /**
         * Beperkte varianten binnen het vaste pagina-ontwerp.
         */
        appearance?: {
          background?: ('default' | 'white' | 'blue' | 'yellow' | 'pink' | 'green') | null;
          spacing?: ('compact' | 'normal' | 'spacious') | null;
          width?: ('narrow' | 'standard' | 'wide') | null;
          alignment?: ('left' | 'center') | null;
          headingSize?: ('small' | 'medium' | 'large') | null;
          /**
           * Optioneel anker voor navigatielinks, bijvoorbeeld “agenda”.
           */
          anchor?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Decoratieve afbeeldingen worden door schermlezers overgeslagen.
   */
  isDecorative?: boolean | null;
  /**
   * Beschrijf de inhoud en functie van de afbeelding in de gekozen taal.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Bepaalt welk deel zichtbaar blijft wanneer de afbeelding wordt bijgesneden.
   */
  focalPosition?: {
    x?: number | null;
    y?: number | null;
  };
  /**
   * Fotograaf, maker of herkomst.
   */
  source?: string | null;
  capturedAt?: string | null;
  containsPeople?: boolean | null;
  /**
   * Bevestig dat herkenbare personen publicatie hebben toegestaan.
   */
  publicationConsent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  summary?: string | null;
  startsAt: string;
  endsAt?: string | null;
  allDay?: boolean | null;
  location?: string | null;
  eventType?: ('largeGroup' | 'smallGroup' | 'wild' | 'vlaanderen' | 'other') | null;
  image?: (number | null) | Media;
  /**
   * Bepaalt waar “meer info” in de agenda en de kalender naartoe wijst. “Geen pagina” toont de activiteit zonder link.
   */
  detail?: ('page' | 'external' | 'none') | null;
  /**
   * Adres van de activiteitpagina, bijvoorbeeld “kringavond-kerst”. Laat leeg om het uit de titel af te leiden.
   */
  slug?: string | null;
  detailUrl?: string | null;
  registrationMode?: ('none' | 'internal' | 'external') | null;
  registrationUrl?: string | null;
  /**
   * Laat leeg voor onbeperkte plaatsen.
   */
  capacity?: number | null;
  waitlistEnabled?: boolean | null;
  registrationOpensAt?: string | null;
  registrationDeadline?: string | null;
  registrationClosedMessage?: string | null;
  /**
   * Bevestig dat actieve inschrijvingen en wachtlijstplaatsen op de achtergrond worden geannuleerd.
   */
  confirmRegistrationClosure?: boolean | null;
  registrationClosurePendingAt?: string | null;
  registrationClosureReason?: ('unpublished' | 'modeChanged' | 'upstreamCancelled') | null;
  source?: ('manual' | 'google') | null;
  externalId?: string | null;
  externalUrl?: string | null;
  lastSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Persoonsgegevens worden twaalf maanden na de activiteit automatisch geanonimiseerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  locale: 'nl' | 'en';
  status: 'confirmed' | 'waitlisted' | 'cancelled' | 'anonymized';
  cancelledAt?: string | null;
  adminNotes?: string | null;
  activeKey?: string | null;
  cancellationTokenHash?: string | null;
  lifecycleTransitionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Duurzame e-mailwachtrij. Mislukte berichten worden automatisch opnieuw geprobeerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-deliveries".
 */
export interface RegistrationDelivery {
  id: number;
  registration: number | Registration;
  event: number | Event;
  kind:
    | 'confirmed'
    | 'waitlisted'
    | 'promoted'
    | 'cancelled'
    | 'eventCancelled'
    | 'registrationClosed'
    | 'registrationChanged';
  status: 'pending' | 'processing' | 'sent' | 'failed';
  attempts: number;
  nextAttemptAt?: string | null;
  lockedAt?: string | null;
  lockToken?: string | null;
  sentAt?: string | null;
  providerMessageId?: string | null;
  lastError?: string | null;
  idempotencyKey: string;
  encryptedPayload?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'registrationManager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'registration-deliveries';
        value: number | RegistrationDelivery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  navigationLabel?: T;
  navigationOrder?: T;
  sectionTitle?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              highlight?: T;
              intro?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              artStyle?: T;
              image?: T;
              curatedPhoto?: T;
              curatedPhotoAlt?: T;
              imagePosition?: T;
              accent?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        values?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              heading?: T;
              body?: T;
              items?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              image?: T;
              layout?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        poster?:
          | T
          | {
              heading?: T;
              highlight?: T;
              title?: T;
              accent?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        eventsList?:
          | T
          | {
              heading?: T;
              intro?: T;
              emptyMessage?: T;
              emptyLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              limit?: T;
              selection?: T;
              events?: T;
              calendarLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        calendar?:
          | T
          | {
              heading?: T;
              intro?: T;
              emptyMessage?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              heading?: T;
              highlight?: T;
              body?: T;
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              accent?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              body?: T;
              attribution?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              primaryLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryLink?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              accent?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaGrid?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        networkLinks?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    name?: T;
                    url?: T;
                    logo?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        photoStory?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    photo?: T;
                    alt?: T;
                    id?: T;
                  };
              layout?: T;
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        infoCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    detail?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          type?: T;
                          page?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              appearance?:
                | T
                | {
                    background?: T;
                    spacing?: T;
                    width?: T;
                    alignment?: T;
                    headingSize?: T;
                    anchor?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  startsAt?: T;
  endsAt?: T;
  allDay?: T;
  location?: T;
  eventType?: T;
  image?: T;
  detail?: T;
  slug?: T;
  detailUrl?: T;
  registrationMode?: T;
  registrationUrl?: T;
  capacity?: T;
  waitlistEnabled?: T;
  registrationOpensAt?: T;
  registrationDeadline?: T;
  registrationClosedMessage?: T;
  confirmRegistrationClosure?: T;
  registrationClosurePendingAt?: T;
  registrationClosureReason?: T;
  source?: T;
  externalId?: T;
  externalUrl?: T;
  lastSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  locale?: T;
  status?: T;
  cancelledAt?: T;
  adminNotes?: T;
  activeKey?: T;
  cancellationTokenHash?: T;
  lifecycleTransitionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-deliveries_select".
 */
export interface RegistrationDeliveriesSelect<T extends boolean = true> {
  registration?: T;
  event?: T;
  kind?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  lockedAt?: T;
  lockToken?: T;
  sentAt?: T;
  providerMessageId?: T;
  lastError?: T;
  idempotencyKey?: T;
  encryptedPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  isDecorative?: T;
  alt?: T;
  caption?: T;
  focalPosition?:
    | T
    | {
        x?: T;
        y?: T;
      };
  source?: T;
  capturedAt?: T;
  containsPeople?: T;
  publicationConsent?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  footerLogo?: (number | null) | Media;
  logoAlt?: string | null;
  navigation?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  dutchLabel?: string | null;
  englishLabel?: string | null;
  footerLine?: string | null;
  footerLinks?:
    | {
        link: {
          label: string;
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  instagramUrl?: string | null;
  whatsappUrl?: string | null;
  facebookUrl?: string | null;
  contactFormUrl?: string | null;
  calendarUrl?: string | null;
  defaultDescription?: string | null;
  defaultImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  footerLogo?: T;
  logoAlt?: T;
  navigation?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  dutchLabel?: T;
  englishLabel?: T;
  footerLine?: T;
  footerLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  email?: T;
  instagramUrl?: T;
  whatsappUrl?: T;
  facebookUrl?: T;
  contactFormUrl?: T;
  calendarUrl?: T;
  defaultDescription?: T;
  defaultImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}